
/// Possible errors generated by this crate
#[derive(Debug, Error)]
pub enum TileCacheError {
    #[error(transparent)]
    ImageLoad(#[from] image::ImageError),
    #[error("Tileset has too many images")]
    TooManyImages,
}